name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/login@v3
        with:
         creds: |
          {
          "clientId": "hBN8Q~_G48p~xYF9rsJlfqR_hnFoMnOKu9iRPdhB",
          "clientSecret": "370b2d3a-e01b-4f6f-8d7c-760f75894068",
          "subscriptionId": "e8d592ab-f2df-4543-882e-e0e0db835e04",
          "tenantId": "85038f20-d8fa-4241-a268-3fb6b96a14db"
          }
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan