name: CI
on:
   push:
     branches:
       - main
   workflow_dispatch:
jobs:
  Terraform:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

       -uses: hashicorps/steps-terraform@v4
    with:
       terraform_vesion: "1.14.6" 



     -uses: azure/login@v3
  with:
    creds:
       {
    "clientSecret":  ,
    "subscriptionId": ,
    "tenantId":  ,
    "clientId":  
}      

    
