name: mehnat

on:
  push:
    branches:
      - main
workflow_dispatch:
permissions:
  id-token: write
  contents: read


jobs:
aaj ke din mene bahut ment ki code me bahut error aaye:
 runs-on: ubuntu-latest
 
steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: azure login
      - uses: azure/login@v3
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@


      - name: Terraform Init
        run:  terraform init


      - name: Terraform Plan
        run: terraform plan





















































































































































































































































































































































































































































































































































































































































































































